openapi: 3.0.0
info:
  title: Videowall XLSX-template Management API
  version: 1.0.0
  description: >-
    API to manage XLSX templates including uploading, deleting, updating, and retrieving templates with an HTML representation.
tags:
  - name: XLSX-template
paths:
  /templates:
    get:
      tags:
        - XLSX-template
      summary: Retrieve all templates
      operationId: getTemplates
      responses:
        '200':
          description: List of templates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemplateListResponse'
    post:
      tags:
        - XLSX-template
      summary: Upload a new template
      operationId: uploadTemplate
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadTemplateRequest'
      responses:
        '201':
          description: Template uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadTemplateResponse'
  /templates/{id}:
    get:
      tags:
        - XLSX-template
      summary: Retrieve a template as HTML string
      operationId: getTemplateAsHtml
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Template HTML representation
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/TemplateHtmlResponse'
    put:
      tags:
        - XLSX-template
      summary: Update a template by ID
      operationId: updateTemplate
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdateTemplateRequest'
      responses:
        '200':
          description: Template updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateTemplateResponse'
    delete:
      tags:
        - XLSX-template
      summary: Delete a template by ID
      operationId: deleteTemplate
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Template deleted successfully
components:
  schemas:
    TemplateListResponse:
      type: object
      properties:
        templates:
          type: array
          items:
            $ref: '#/components/schemas/TemplateDto'
    TemplateDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        version:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    UploadTemplateRequest:
      type: object
      properties:
        file:
          type: string
          format: binary
          description: XLSX file to upload
        name:
          type: string
          description: Custom name for the template
      required:
        - file
        - name
    UploadTemplateResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        version:
          type: integer
        created_at:
          type: string
          format: date-time
    UpdateTemplateRequest:
      type: object
      properties:
        file:
          type: string
          format: binary
          description: XLSX file to update
        name:
          type: string
          description: New custom name for the template
    UpdateTemplateResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        version:
          type: integer
        updated_at:
          type: string
          format: date-time
    TemplateHtmlResponse:
      type: string
      description: >-
        HTML representation of the template as a string with 
        `<table>`, `<tr>`, and `<td>` tags.
